78680 more unit tests
equinor/procosys-preservation-api pull request #428
Opened 2020-10-13 08:16 UTC by janid1967

Added some missing tests, detecting when working with IPO/PO

2020-10-13 14:00 UTC, Cnordbo requested changes

2020-10-13 14:00 UTC, Cnordbo commented on src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Permission/MainApiPermissionServiceTests.cs
> +        public async Task GetAllProjectsAsync_ShouldReturnThreeProjects_OnValidPlant()
"Should return three projects", but assertion is on "2"

2020-10-13 14:00 UTC, Cnordbo commented on src/tests/Equinor.Procosys.Preservation.MainApi.Tests/Permission/MainApiPermissionServiceTests.cs
> +        public async Task GetAllProjectsAsync_ShouldReturnNoProjects_OnInValidPlant()
invalid is "one word" (camelcasing)

2020-10-14 06:39 UTC, janid1967 commented on src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Misc/ProjectCheckerTests.cs
> +            await _dut.EnsureValidProjectAsync(_testRequest);
How can we assert when it's nothing to Assert on? The test verify that code execute without exception

2020-10-14 07:37 UTC, janid1967 commented on src/tests/Equinor.Procosys.Preservation.WebApi.Tests/Misc/ProjectCheckerTests.cs
> +            await _dut.EnsureValidProjectAsync(_testRequest);
Also discussed with @llykkelarsen ... we think test is ok as is ... won't fix

2020-10-14 08:20 UTC, Cnordbo approved these changes

2020-10-14 08:21 UTC, merged