Feature/76112 replace preservation polling service
equinor/procosys-preservation-api pull request #541
Opened 2021-05-05 13:17 UTC by paal123

Replacing sync service for all types except auto transfer tags.

DevOps#76112

2021-05-07 06:08 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        public void DetachFromProject(Tag tag)
I didn't like that DetachFromProject is a public method, since calling this method alone and Save will make an illegal state.
I suggest rename this method to MoveTag, and take in the destination Project to move to and rewrite these 2 lines in ProjectRepo:
![image](https://user-images.githubusercontent.com/19545528/117405149-6b9ec380-af0b-11eb-80a4-c253cce88f77.png)
... to be a oneliner MoveTag

2021-05-07 06:15 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        public void DetachFromProject(Tag tag)
Theoretically the target project can already have a Tag with same name, which will cause an illegal state (Code in preservation select items using LINQ Single() and SingleOrDefault() -> exception )

So the move operation should fail if so

2021-05-07 06:21 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +
remove

2021-05-07 06:22 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        public void MoveMcPkg(string mcPkgNo, string fromCommPkg, string toCommPkg)
RenameCommPkg

2021-05-07 06:22 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        public void RenameMcPkg(string fromMcPkgNo, string toMcPkgNo, string commPkgNo)
make commPkgNo as first param (to match method above)

2021-05-07 06:27 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/ProjectTests.cs
> +            // Assert
Arrange here and remove 119 ... (yes it is asserts, but as a part of arranging the test)
Same on 144

2021-05-07 06:29 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
> +                throw new Exception("Not allowed to blank out tag no!");
"missing argument {nameof(newTagNo)}"

2021-05-07 06:31 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/TagFunctionAggregate/TagFunction.cs
> +                throw new ArgumentNullException($"RenameTagFunction: Missing arguments {newCode} - {newRegisterCode}");
ArgumentNullException($"{nameof(newCode)} or {nameof(newRegisterCode)}"

2021-05-07 06:33 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Infrastructure/Repositories/ProjectRepository.cs
> +            tagsToMove.ForEach(t => toProject.AddTag(t));
ref other comment: change 76/77 to:
tagsToMove.ForEach(t => fromProject.MoveTag(t, toProject));

2021-05-07 07:01 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> +            if (string.IsNullOrWhiteSpace(tagEvent.Plant) ||
also check for tagEvent == null (Resharper complains on possible nulpointer ex on tagEvent.Plant)
Same goes for line 110, 145, 171 210,

2021-05-07 07:03 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> +                (string.IsNullOrWhiteSpace(mcPkgEvent.McPkgNoOld) != (string.IsNullOrWhiteSpace(mcPkgEvent.CommPkgNoOld))))
take this ckeck out of this if and make its own below to give another type of Exception with another message about "illegal with blah blah" ?

2021-05-07 07:17 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Repositories/ProjectRepositoryTests.cs
> +            await _dut.MoveCommPkgAsync(CommPkg1, "Unknown from project", ProjectNameWithTags);
expr.body

2021-05-07 07:17 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Repositories/ProjectRepositoryTests.cs
> +            await _dut.MoveCommPkgAsync(CommPkg1, ProjectNameWithTags, "Unknown project");
expr.body

2021-05-07 07:17 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
> +        private Mock<Project> _project3;
remove

2021-05-07 07:21 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
> +            var message = $"{{}}";
remove redundant string interpolation?

2021-05-07 07:22 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
> +            var message = $"{{}}";
same on many other similar codelines below

2021-05-07 07:23 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
> +            string message =
var

2021-05-07 07:23 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
> +            string message =
var

2021-05-07 07:23 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
> +            string message =
var

2021-05-07 07:23 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.WebApi.Tests/Synchronization/BusReceiverServiceTests.cs
> +            string message =
var

2021-05-07 07:24 UTC, janid1967 requested changes
See comments

2021-05-18 11:56 UTC, paal123 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        public void MoveMcPkg(string mcPkgNo, string fromCommPkg, string toCommPkg)
This is not a rename of a comm pkg. as the comm pkg might still be there, but the tags with the given commpkg and mcpkg get a new commpkgno.

2021-05-20 08:27 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        public void DetachFromProject(Tag tag)
Remove unused method (and the test)

2021-05-20 08:52 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
> +                if (_isVoided == value)
I guess this is to prevent adding an event when no changes done?
I'll add unit tests to proof that we don't add new events when _isVoided are not changed

2021-05-20 09:01 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.Command.Tests/Validators/TagValidatorTests.cs
> +                La til taggen under med nytt tagno siden jeg la på regel om at tagno ikke kan eksistere fra før.  er dette korrekt?
Fine. Yes, previous setup was incorrect!

2021-05-20 09:02 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.Domain.Tests/AggregateModels/ProjectAggregate/ProjectTests.cs
> +        private Tag _tag, _tag2;
prefer 2 lines (and maybe a rename from _tag to _tag1)

2021-05-20 09:10 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests/Repositories/ProjectRepositoryTests.cs
> +        private Tag _standardTag1With3Reqs, _standardTag2;
2 lines

2021-05-20 09:10 UTC, janid1967 approved these changes
Approved w suggestions

2021-05-20 12:22 UTC, paal123 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Project.cs
> +            if (_tags.Any(t => t.TagNo == tag.TagNo))
Resharper does not give any complaints for me...

2021-05-20 12:37 UTC, paal123 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> +                (string.IsNullOrWhiteSpace(mcPkgEvent.McPkgNoOld) != (string.IsNullOrWhiteSpace(mcPkgEvent.CommPkgNoOld))))
Adjusted the text some. Since all of these will always produce a "correct" deserialization, but the event is in an invalid state if any of these are missing or in incorrect combination

2021-05-25 12:35 UTC, merged