Refresh app configuration when sentinel value changes
equinor/procosys-preservation-api pull request #665
Opened 2021-12-07 08:25 UTC by chormaz

The app configuration settings are now updated 30 secs. after a change in the sentinel value is done in Azure App Configuration.

2021-12-07 09:50 UTC, janid1967 commented
Remove my test-configs named Authenticator:GlobalSetting and Authenticator:ScopedSetting. Remove both from code + tidy in configs pcs-pres-non-prod-config / pcs-pres-prod-config

2021-12-07 09:50 UTC, janid1967 requested changes
Remove my test-configs named Authenticator:GlobalSetting and Authenticator:ScopedSetting. Remove both from code + tidy in configs pcs-pres-non-prod-config / pcs-pres-prod-config

2021-12-07 12:59 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Authentication/Authenticator.cs
> +        public Authenticator(IOptionsSnapshot<AuthenticatorOptions> options, ILogger<Authenticator> logger)
Why this?

2021-12-07 13:01 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Program.cs
> +                                     refreshOptions.SetCacheExpiration(TimeSpan.FromSeconds(30));
Revert back to 5 minutes.
It's a resaon to use 5 minutes rather than 30 sec. I'll explain the scenario later

2021-12-07 14:20 UTC, chormaz commented on src/Equinor.ProCoSys.Preservation.WebApi/Authentication/Authenticator.cs
> +        public Authenticator(IOptionsSnapshot<AuthenticatorOptions> options, ILogger<Authenticator> logger)
![image](https://user-images.githubusercontent.com/78788930/145045905-6f8dde75-d3ed-4c5b-8d3e-3e83e83a267f.png)

2021-12-08 07:19 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Authentication/Authenticator.cs
> +        public Authenticator(IOptionsSnapshot<AuthenticatorOptions> options, ILogger<Authenticator> logger)
As mentioned yesterday: Then all use of IOptionMonitor need to be replaced

2021-12-09 12:28 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Middleware/VerifyPreservationApiClientExists.cs
> +        private readonly IOptionsMonitor<AuthenticatorOptions> _options;
Yet another type of IOptions-stuff .. so why this type needed just here, and no other place where you started to use IOptionsSnapshot

2021-12-09 12:52 UTC, chormaz commented on src/Equinor.ProCoSys.Preservation.WebApi/Middleware/VerifyPreservationApiClientExists.cs
> +        private readonly IOptionsMonitor<AuthenticatorOptions> _options;
We can't use IOptionsSnapshot for Hosted Services. The difference between the two is that IOptionsSnapshot keeps the value through out the execution of a request whilst IOptionsMonitor can change the current value during the execution of a request. The chance for it to cause real-life errors is close to zero. Therefore the change of type.

2021-12-09 13:13 UTC, janid1967 approved these changes

2021-12-09 13:14 UTC, merged