96689 Handle delete behavior bus events
equinor/procosys-preservation-api pull request #815
Opened 2022-11-03 13:51 UTC by TordJoranger

AB#96689

2022-11-03 13:53 UTC, TordJoranger commented
Updated minor versions of nuget, left MeditR as it has breaking changes that affects us.

2022-11-03 14:04 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> +
remove

2022-11-03 14:04 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> -            switch (pcsTopic)
undo change

2022-11-03 14:04 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> +
remove

2022-11-03 14:13 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> +            if (deserializedMessage != null && IsDeleteEvent(deserializedMessage))
since this class is changed, please check for null where JsonSerializer.Deserialize is used. Sample 
![image](https://user-images.githubusercontent.com/19545528/199743772-4ea2fbb3-3110-41ef-9b12-7e40d66bc1b3.png)
(6 or 7 places)

2022-11-03 14:14 UTC, janid1967 approved these changes
Approved with suggestions

2022-11-04 06:42 UTC, janid1967 commented on src/Equinor.ProCoSys.Preservation.WebApi/Synchronization/BusReceiverService.cs
> +namespace Equinor.ProCoSys.Preservation.WebApi.Synchronization;
UNDO and revert change ofindent !!!
I'm not a fan of such changes in existing code. "Impossible" to code review and actually see changes of of importance
When creating new class, it's ok to add namespace clause at top.

2022-11-04 06:42 UTC, janid1967 requested changes
See comment

2022-11-07 13:26 UTC, janid1967 approved these changes

2022-11-07 14:13 UTC, merged