Pbi/104952 move preservation api to radix
equinor/procosys-preservation-api pull request #944
Opened 2023-09-28 17:41 UTC by arildbjerkenes

2023-09-29 15:22 UTC, TordJoranger commented on pipelines/api-build-radix.yml
> +      - pbi/104952_Move_Preservation_API_to_Radix
denne må fikses før vi kan merge

2023-09-29 15:24 UTC, TordJoranger commented on pipelines/api-build-radix.yml
> +        vmImage: 'windows-latest'
her er jeg usikker, men burde vi bruke ubuntu? i og med at vi deployer på linux?

2023-09-29 15:25 UTC, arildbjerkenes commented on pipelines/api-build-radix.yml
> +        vmImage: 'windows-latest'
Nope, hadde det først, men fikk feilmelding om at man måtte ha windows.

2023-09-29 15:27 UTC, arildbjerkenes commented on pipelines/api-build-radix.yml
> +      - pbi/104952_Move_Preservation_API_to_Radix
Stemmer det. Glemte å kommentere det. Vi må prate om hvordan vi gjør dette praktisk sett.

2023-09-29 15:27 UTC, arildbjerkenes commented on pipelines/api-build-radix.yml
> +    aspNetCoreEnvironment: 'Development'
Hva mener du her?

2023-09-29 15:28 UTC, TordJoranger commented on pipelines/api-build.yml
> +   value: '${{ variables.containerRegistryName }}.azurecr.io/leader-elector:13'
not latest?

2023-09-29 15:28 UTC, TordJoranger commented on pipelines/api-build.yml
> +      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/pbi/104952_Move_Preservation_API_to_Radix'))
branch name

2023-09-29 15:29 UTC, TordJoranger commented on pipelines/templates/radix-deploy.yml
> +    default: 'procosys - non-prod'
spaces? procosys-non-prod

2023-09-29 15:29 UTC, arildbjerkenes commented on pipelines/api-build.yml
> +      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/pbi/104952_Move_Preservation_API_to_Radix'))
Ja, dette skal fikses.

2023-09-29 15:33 UTC, arildbjerkenes commented on pipelines/api-build.yml
> +   value: '${{ variables.containerRegistryName }}.azurecr.io/leader-elector:13'
Hadde først det, men ved nærmere ettertanke bør vi vel aldri bruke latest. Hvis vi oppdaterer en nuget-pakke, som en annen applikasjon ønsker å ta i bruk, er det ikke sikkert at denne applikasjonen bør bruke denne. Da mister vi kontroll. Sikkert greit med leader elector altså, men prinsipielt tenker jeg at vi må sette en versjon.

2023-09-29 15:35 UTC, TordJoranger commented on radixconfig.yaml
> +        LEADERELECTOR_SERVICE: http://leader-electorTULL:3003
remember to fix b4 merge

2023-09-29 15:36 UTC, TordJoranger commented on src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs
> +                var leaderElectorUrl = Environment.GetEnvironmentVariable("LEADERELECTOR_SERVICE") ?? Configuration["ServiceBus:LeaderElectorUrl"];
revert this, its used locally

2023-09-29 15:37 UTC, TordJoranger commented on pipelines/api-build-radix.yml
> +# Run tests Stage
remove commented code b4 merge

2023-09-29 15:39 UTC, TordJoranger commented on pipelines/api-build-radix.yml
> +    aspNetCoreEnvironment: 'Development'
Hmm, jeg roter.
men,
Vi setter aspNetCoreEnvironment: 'Development', som er bra for dev, men kan vi overskrive denne når vi promoter?

2023-09-29 15:40 UTC, TordJoranger commented on pipelines/api-build.yml
> +   value: '${{ variables.containerRegistryName }}.azurecr.io/leader-elector:13'
makes sense

2023-09-29 15:42 UTC, TordJoranger requested changes
ser bra ut, men må fikse branches osv før vi merger. 

Burde vi ha nemanja på review og? config med memmory oppsett osv blir bare gjetting for min del?

2023-10-01 19:59 UTC, arildbjerkenes commented on pipelines/api-build-radix.yml
> +    aspNetCoreEnvironment: 'Development'
Ah, denne variabelen brukes ikke lenger her! Vi setter verdi radixconfig.yml

2023-10-02 06:13 UTC, arildbjerkenes commented on radixconfig.yaml
> +        LEADERELECTOR_SERVICE: http://leader-electorTULL:3003
Tenker vi gjør det direkte i Radix konfigurasjon, når vi vet at Radix kan ta over å konsumere meldinger.

2023-10-02 06:20 UTC, TordJoranger commented on pipelines/api-build-radix.yml
> +              # Promote to test
typo in comment

2023-10-02 08:04 UTC, TordJoranger commented on src/Equinor.ProCoSys.Preservation.sln
> +		..\pipelines\api-build-radix.yml = ..\pipelines\api-build-radix.yml
her er det krøll

2023-10-02 08:04 UTC, TordJoranger approved these changes

2023-10-04 06:39 UTC, merged