111982 - Fam transfer
equinor/procosys-preservation-api pull request #958
Opened 2024-06-28 09:24 UTC by haavard-hoijord

AB#111982

2024-06-28 09:40 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/ActionCommands/CreateAction/CreateActionCommandHandler.cs
> +                new Guid(),
Guid property ought to be set in Action constructor instead of as parameter in the constructor, see IPO Invitation for example.

2024-06-28 09:59 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/ActionAddedEventHandler.cs
> +                                        where tag.Guid == notification.SourceGuid
I think notification Source.Guid refers to the guid of the Action, and not the Tag, so it cannot be used this way.
ChatGpt says we can find TagId using the following:
     var tagId = _context.Entry(action).Property<int>("TagId").CurrentValue;
and retrieve the tab object using
    var tag = _context.Tags.Find(tagId);
Seems a tiny bit hacky to me, so would like to think it over.

2024-06-28 13:29 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/Events/ActionEvent.cs
> +    public string TagNr { get; }
We don't need TagNr as this will be joined in on FAM side from their Tag table.
But we do need the TagGuid instead, so they can perform that join.

2024-06-28 13:33 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Action.cs
> +        public Guid ObjectGuid { get; private set; }
ObjectGuid and ProCoSysGuid can be removed.
I know I mentioned ProCoSysGuid, so my mistake, it only needs to exist in the message sent to ServiceBus...

2024-06-28 13:35 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.MessageContracts/IActionEventV1.cs
> +    string TagNr { get; }
Replace with TagGuid

2024-06-28 13:38 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.WebApi/Startup.cs
> +                   // .WithLeaderElector(leaderElectorUrl)
I think it works even with this commented in.
At least I got it working in IPO even though it spits out exceptions with a "LeaderElectorUrl": "https://fake.host.com" config.
Just a bit nervous we forget to comment it back in again before deploy...

2024-06-28 13:45 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            action.DueTimeUtc != null ? DateOnly.FromDateTime(action.DueTimeUtc.GetValueOrDefault(DateTime.Now)) : null,
Defaulting to DateTime.Now risks sending over incorrect date, however unlikely.
Better to just use action.DueTimeUtc.Value since we have already done a null check?

2024-06-28 13:48 UTC, jsoi-eq requested changes
See comments.

2024-06-28 17:39 UTC, haavard-hoijord commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Action.cs
> +        public Guid ObjectGuid { get; private set; }
Well Guid is required for the IHaveGuid interface, but i can get rid of the ObjectGuid

2024-07-01 08:16 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Action.cs
>              ProCoSysGuid = Guid;
What I meant was to keep Guid property but remove both ObjectGuid and ProCoSysGuid. 
We only need a property ProCoSysGuid when sending to FAM, and don't need it in the aggregate, that was my miscommunication last time around.

2024-07-01 08:24 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/ActionClosedEventHandler.cs
> +        var actionObject = await (from action in _context.QuerySet<Action>()
I realized that in IPO latest version we are sending in the whole object in the Notification.
So instead of sending in actionGuid, you can send in the entire Action object.
Then you don't need to query for it again in this method.

2024-07-01 10:44 UTC, haavard-hoijord commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/ActionClosedEventHandler.cs
> +        var actionObject = await (from action in _context.QuerySet<Action>()
I am not quite sure i understood what you meant here

2024-07-01 13:16 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +    public async Task<IActionEventV1> CreateActionEvent(Action action, Guid tagId)
Could you use tagGuid as the parameter name instead?
We have two "id" columns in Tag, Id and Guid.
For me I get confused with the name tagId since I assume this refers to Tag.Id, and not Tag.Guid.
The same tagId -> tagGuid applies for some of the other files below.

Also matches with the existing convention where sourceGuid is used instead of sourceId

2024-07-01 13:33 UTC, jsoi-eq requested changes
Looks good, only the tagId -> tagGuid rename, left.

2024-07-04 10:14 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +    public async Task SendTagRequirementEvents(TagRequirement tagRequirement, Guid tagGuid, CancellationToken cancellationToken)
This method is not in use and can be removed?

2024-07-04 10:22 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            CreatedById = tagRequirement.CreatedById,
Instead of TagRequirement.CreatedById, change this to TagRequirement.CreatedByGuid instead. 
So you need to read Guid property  value from the Person table based on the CreatedById, see IPO code for an example.
This guid contains the Azure Oid of a user, and will be used in FAM for a lookup on their side to get name and email-address etc.

2024-07-04 10:22 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            ModifiedById = tagRequirement.ModifiedById,
=> ModifiedByGuid

2024-07-04 10:24 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +    public async Task<IPreservationPeriodEventV1> CreatePreservationPeriodEvent(PreservationPeriod preservationPeriod)
Remove async if we don't use any await.

2024-07-04 10:28 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            PreservationRecord =
Don't use nested structures, we don't handle those in FamWebJob.
Is PreservedById used for a join somewhere else? We usually don't send over internal int id values unless there is a specific reason, like in IPO we send it over since it is used for generating a title.
Curious: What was the motivation for doing these as a dynamic?

2024-07-04 10:30 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            FieldId = field.Id,
I don't think we need FieldId since we have Guid here?

2024-07-04 10:31 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +    public async Task<IFieldEventV1> CreateFieldEvent(Field field, Guid sourceGuid) =>
Remove async

2024-07-04 10:31 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            CreatedById = field.CreatedById,
=> CreatedByGuid

2024-07-04 10:31 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            ModifiedById = field.ModifiedById,
ModifiedByGuid

2024-07-04 10:32 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +    public async Task<IRequirementDefinitionEventV1> CreateRequirementDefinitionEvent(RequirementDefinition requirementDefinition) =>
Remove async

2024-07-04 10:32 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +    public async Task<IRequirementTypeEventV1> CreateRequirementTypeEvent(RequirementType requirementType) =>
Remove async

2024-07-04 10:33 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            CreatedById = requirementType.CreatedById,
CreatedByGuid

2024-07-04 10:33 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/CreateEventHelper.cs
> +            ModifiedById = requirementDefinition.ModifiedById
ModifiedByGuid

2024-07-04 10:48 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/Events/DeleteEvent.cs
> +public class DeleteEvent : IDeleteEventV1
Is this published to the correct topic on servicebus?
An ActionDelete message should be published to the action topic, TagDelete to Tag topic etc, will this happen when using a generic DeleteEvent like this?

2024-07-04 10:48 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/Events/FieldEvent.cs
> +    public int FieldId { get; set; }
Not required since we have a Guid property?

2024-07-04 10:49 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/Events/FieldEvent.cs
> +    public int CreatedById { get; set; }
You know the drill by now ;), I will not write any more comments for CreatedById and ModifiedById from now onwards.

2024-07-04 10:51 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/Events/PreservationPeriodsEvent.cs
> +    public string ProjectName { get; set; } = "";
If we don't have a projectname, I think we can remove the property unless there is a reason to keep it?

2024-07-04 10:53 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/Events/PreservationRecordEvent.cs
> +public class PreservationRecordEvent : IPreservationRecordEventV1
Need a Guid property. 
May need a Plant property, not sure, we need to look into that, as I realize this is across all plants master data.

2024-07-04 10:55 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/Events/PreservationRecordEvent.cs
> +    public int PreservedById { get; set; }
PreservedByGuid, in case you did a search replace for CreatedById and ModifiedById and missed this one.

2024-07-04 11:15 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Action.cs
> +        public Guid TagGuid { get; set; }
I need to think a little bit about this one. 
We already have a reference to Tag with TagId, although I see it is hidden.
Introducing this would lead to an extra column in the database, and us having basically two references to Tag, one by Id and one by Guid.
If we do add this, at least it has to be non-nullable, which also leads to a job populating this column in database with correct values, and having a constraint so we can't add values not existing in Tag.Guid column.

2024-07-04 11:16 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/PreservationPeriod.cs
> +        public Guid TagRequirementGuid { get; set; }
Reminder to self to think about about whether we want the extra TagRequirementGuid column.

2024-07-04 11:32 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/TagRequirement.cs
> +        public Guid RequirementDefinitionGuid { get; private set; }
Note to self: Consider whether we want this property.

2024-07-04 11:33 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/Field.cs
> +        public Guid RequirementDefinitionGuid { get; set; }
Note to self: Consider whether we want this property.

2024-07-04 11:33 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/RequirementTypeAggregate/RequirementDefinition.cs
> +        public Guid RequirementTypeGuid { get; set; }
Note to self: vConsider whether we want this property.

2024-07-04 11:41 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementAddedEvent.cs
> +        public int RequirementDefinitionId => TagRequirement.RequirementDefinitionId;
Was there a reason for Id instead of Guid?

2024-07-04 11:41 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementDeletedEvent.cs
> +        public int RequirementDefinitionId => TagRequirement.RequirementDefinitionId;
Was there a reason for Id instead of Guid?

2024-07-04 11:41 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementPreservedEvent.cs
> +        public int RequirementDefinitionId => TagRequirement.RequirementDefinitionId;
Was there a reason for Id instead of Guid?

2024-07-04 11:42 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementUnvoidedEvent.cs
> +        public int RequirementDefinitionId => TagRequirement.RequirementDefinitionId;
Was there a reason for Id instead of Guid?

2024-07-04 11:43 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/Events/TagRequirementUpdatedEvent.cs
> +        public int RequirementDefinitionId => TagRequirement.RequirementDefinitionId;
Was there a reason for Id instead of Guid?

2024-07-04 11:45 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Infrastructure/Migrations/20240701141306_AddMassTransitAndGuids.cs
> +            migrationBuilder.AddColumn<Guid>(
Note to self: Consider removing the new Guid columns from here and let MassTransit be one migration and Guids a different migration.

2024-07-04 11:46 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Infrastructure/Migrations/20240702092142_AddGuidsToRequirementsAndField.cs
> +            migrationBuilder.AddColumn<Guid>(
Note to self: All these Guids need to be populated with initial values

2024-07-04 14:36 UTC, haavard-hoijord commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
Yes, so this change here just moved the added event from the AddRequirement to the SetCreated method, which is activated by changes in the database instead of the AddRequirement function

2024-07-05 07:03 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
Regarding changes for Area or Discipline, I see your point for SetModified which sends out a TagUpdatedEvent when a change has happened, and for new ones we have TagCreatedEvent in constructor, and I agree.

And I see now what you did with TagRequirementAddedEvent, and I agree it makes sense to move it, although I wonder if it makes more sense to put it in the constructor in TagRequirement, similar to what is done with TagCreatedEvent in Tag.

2024-07-05 07:27 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/HistoryEvents/ActionAddedEventHandler.cs
> +        public ActionAddedEventHandler(IHistoryRepository historyRepository, IProjectRepository projectRepository, PreservationContext context)
It seems from other places in the code that we should not use PreseverationContext directly, but rather IReadOnlyContext. Then we also don't need the dependency to Infrastructure which was added.
So something like 
            var tagId = await _readOnlyContext.QuerySet<Action>().Where(s => s.Guid == notification.TagRequirement.Guid)
                .Select(s => EF.Property<int>(s, "TagId")).SingleAsync(cancellationToken: cancellationToken);

Hopefully works?
Applies for all HistoryEvents that you changed.

2024-07-05 07:30 UTC, haavard-hoijord commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
Well putting it in the constructor does have a theoretical issue in that the event could be run before it has actually been saved to the database so querying for the tag id or similar would fail

2024-07-05 08:22 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
Hmm, so you're saying that if we are creating a new tag, and then adding a requirement, the tag will have Id = 0 because a savechanges has not been called to populate the Id value, sounds plausible, good catch.
And in SetCreated we know savechanges has been called so we do have an Id at that point in time.
I retract my suggestion to move it to constructor.
Although maybe add a comment since this was non-intuitive?

2024-07-05 09:33 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/PreservationPeriodDeletedEventHandler.cs
> +        var deleteEvent = new DeleteEvent.PreservationPeriodDeleteEvent(notification.PreservationPeriod.Guid, notification.PreservationPeriod.Plant, "");
I think NULL may be a better representation than empty string, when it comes to the FAM database.

2024-07-05 09:33 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/RequirementDefinitionDeletedEventHandler.cs
> +        var deleteEvent = new DeleteEvent.RequirementDefinitionDeleteEvent(notification.RequirementDefinition.Guid, notification.RequirementDefinition.Plant, "");
Same

2024-07-05 09:34 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/RequirementFieldDeletedEventHandler.cs
> +        var deleteEvent = new DeleteEvent.RequirementFieldDeleteEvent(notification.Field.Guid, notification.Field.Plant, "");
Same

2024-07-05 09:34 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventHandlers/IntegrationEvents/RequirementTypeDeletedEventHandler.cs
> +        var deleteEvent = new DeleteEvent.RequirementTypeDeleteEvent(notification.RequirementType.Guid, notification.RequirementType.Plant, "");
Same

2024-07-05 09:41 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Preservation.Command/EventPublishers/BusEventMessage.cs
>      public Guid ProCoSysGuid => Guid;
I see IIntegrationEvent received 
Guid ProCoSysGuid => Guid;
Which is fine.
But do we need this line anymore in BusEventMessage then?

2024-09-25 11:33 UTC, richard1927 commented on src/Equinor.ProCoSys.Preservation.Command/Events/DeleteEvent.cs
> +public class DeleteEvent : IDeleteEventV1
It does not look like IDeleteEventV1 events are handled, so they will not be published to any topic. I think they would throw an error.

2024-09-25 11:53 UTC, richard1927 commented on src/Equinor.ProCoSys.Preservation.Command/Events/DeleteEvent.cs
> +public class DeleteEvent : IDeleteEventV1
Actually, it does not look like they would throw an error. It looks like all events go to the "IIntegrationEvent" topic. I will investigate further.

2024-09-25 12:14 UTC, richard1927 commented on src/Equinor.ProCoSys.Preservation.Command/Events/DeleteEvent.cs
> +public class DeleteEvent : IDeleteEventV1
It looks like the EntityNames attributes specify what queues the messages go to. ActionDelete should go to the PreservationAction topic, and TagDelete should go to the PreservationTag topic.

2024-09-25 12:26 UTC, richard1927 commented on src/Equinor.ProCoSys.Preservation.Command/Events/DeleteEvent.cs
> +public class DeleteEvent : IDeleteEventV1
Local testing results in a argument exception when evaluating what topic to use. I will fix this.

2024-10-15 09:11 UTC, richard1927 commented on src/Equinor.ProCoSys.Preservation.Domain/AggregateModels/ProjectAggregate/Tag.cs
Resolving conversation. This will be refactored completely when making the change to pre save events.

2024-10-15 10:29 UTC, jsoi-eq approved these changes

2024-10-15 10:46 UTC, merged